# Generated by Django 2.0 on 2017-12-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='element',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='monster',
            name='full_name',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='monster',
            name='get_from',
            field=models.CharField(default='', max_length=200, verbose_name='Get From'),
        ),
        migrations.AddField(
            model_name='monster',
            name='good_for',
            field=models.CharField(default='', max_length=200, verbose_name='Good For'),
        ),
        migrations.AddField(
            model_name='monster',
            name='grade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='monster',
            name='grade_num',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Grade Number'),
        ),
        migrations.AddField(
            model_name='monster',
            name='mon_type',
            field=models.CharField(default='', max_length=25, verbose_name='Monster Type'),
        ),
        migrations.AddField(
            model_name='monster',
            name='score_total',
            field=models.FloatField(default=0, verbose_name='Total Score'),
        ),
        migrations.AddField(
            model_name='monster',
            name='score_user',
            field=models.FloatField(default=0, verbose_name='User Score'),
        ),
        migrations.AddField(
            model_name='monster',
            name='skillup_info',
            field=models.CharField(default='', max_length=200, verbose_name='Skillup Information'),
        ),
        migrations.AddField(
            model_name='monster',
            name='sleepy_name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Sleepy Name'),
        ),
        migrations.AddField(
            model_name='monster',
            name='when_awakened',
            field=models.CharField(default='', max_length=200, verbose_name='When Awakened'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='awaken_name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Awakened Name'),
        ),
    ]
